services:
  nats:
    image: nats:2.10-alpine
    container_name: msngr_nats
    restart: unless-stopped
    ports:
      - "4222:4222"
    command: ["-m", "8222"]
    networks:
      - msngr-network

  postgres:
    image: postgres:16-alpine
    container_name: messaging_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d messaging_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - msngr-network
    
  app:
    container_name: message-service
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      NATS_URL: ${NATS_URL:-nats://nats:4222}
    depends_on:
      nats:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - msngr-network

volumes:
  postgres_data:

networks:
  msngr2-network:
    # external: true